// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFWIHFvAeGQDM_MZhq9CPPq0eU5CZQxY',
    appId: '1:206251435447:web:6e600c64ec0652d52eb432',
    messagingSenderId: '206251435447',
    projectId: 'ayotani-4a6c7',
    authDomain: 'ayotani-4a6c7.firebaseapp.com',
    storageBucket: 'ayotani-4a6c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9SlKnG7uhURl8WTKG88_gtCbQEye-eg',
    appId: '1:206251435447:android:9d1ad44703011db42eb432',
    messagingSenderId: '206251435447',
    projectId: 'ayotani-4a6c7',
    storageBucket: 'ayotani-4a6c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlILxh9oyP0jiCS5nySpjips38bHEhJdY',
    appId: '1:206251435447:ios:e75224bc7cc488e12eb432',
    messagingSenderId: '206251435447',
    projectId: 'ayotani-4a6c7',
    storageBucket: 'ayotani-4a6c7.appspot.com',
    iosBundleId: 'com.example.ayotani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlILxh9oyP0jiCS5nySpjips38bHEhJdY',
    appId: '1:206251435447:ios:e75224bc7cc488e12eb432',
    messagingSenderId: '206251435447',
    projectId: 'ayotani-4a6c7',
    storageBucket: 'ayotani-4a6c7.appspot.com',
    iosBundleId: 'com.example.ayotani',
  );
}
